# Generated by Django 5.1.4 on 2025-08-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_remove_license_is_active_remove_license_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_request_email', models.EmailField(blank=True, help_text='This email will receive all kinds of new license requests from users.', max_length=254, null=True, verbose_name='License Request Email')),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
    ]
