# Generated by Django 5.1.4 on 2025-08-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_adminsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name_plural': 'Licenses'},
        ),
        migrations.AddField(
            model_name='license',
            name='view_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='view_password_salt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
